### PR TITLE
Сonway primitives fix

### PR DESCRIPTION
**Pull request by lisicky**
CDDL changes: 
  - NewCommittee was renamed to UpdateCommittee
  - Committee was deleted
 
Update plutus v3 related structs
I also added a test with manually constructed block with a tx which contains all conway certs, voting proposals and voting procedures

### CODE REVIEW

**Review by jmhrpr — APPROVED** [review]

**Comment by jmhrpr** [comment]
Where are you finding the new RedeemerTag @lisicky? I dont see it in the CDDL:

```
    #[n(5)]
    VotingProposal, 
```

**Comment by lisicky** [comment]
@Ryun1 could you confirm that will be a new redeemer tag for VotingProposal ? If not I'll delete it from CSL too

**Comment by Ryun1** [comment]
Response from Ledger team (@lehins) on this:

Yes, it is still not implemented, since PlutusV3 integration is not done yet.
Expect there to be two extra tags 4 and 5.
We are currently working on this, but it will take time.

**Comment by lisicky** [comment]
Thanks @Ryun1 ! @jmhrpr could you update your PR on txpipe repo ?

**Pull request merged**
